builders:
  - python
upstream:
  - eduid-userdb
  - eduid-common
  - eduid-IdP-html
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
python_module: eduid_idp
clean_workspace: true
publish_over_ssh:
  - pypi.sunet.se

extra_jobs:
  - name: eduid-IdP-docker
    builders:
      - docker
    docker_name: eduid/eduid-idp
    managed_scripts:
      - docker_build_prep.sh
      - docker_tag.sh
    triggers:
      github_push: false
      cron: null
    upstream:
      - eduid-docker-pythonenv
      - eduid-IdP
