builders:
  - script
upstream:
  - eduid-userdb
  - eduid-common
  - eduid-IdP-html
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
python_module: eduid_idp
pre_build_script:
  - apt-get install -y xmlsec1
clean_workspace: true
publish_over_ssh:
  - pypi.sunet.se

script:
  - "python3 -m venv venv"
  - ". venv/bin/activate"
  - "pip install -U setuptools"
  - "pip install --index-url https://pypi.sunet.se -r test_requirements.txt"
  - "nosetests"
  - "python setup.py sdist bdist_wheel --universal"

extra_jobs:
  - name: eduid-IdP-docker
    builders:
      - docker
    docker_name: eduid/eduid-idp
    managed_scripts:
      - docker_build_prep.sh
      - docker_tag.sh
    triggers:
      github_push: false
      cron: null
    pre_build_script: ~
    upstream:
      - eduid-docker-python3env
      - eduid-IdP
