sudo: required
addons:
  apt:
    packages:
      xmlsec1  # pysaml2 needs to find an xmlsec1 binary
#      libxml2-dev
#      libxslt1-dev
#      zlib1g-dev
#      xmlsec1
#      libxml2-utils
#      libffi-dev
#      libssl-dev
language: python
python:
  - "2.7"
#  - "3.5"
# Have Travis CI start a mongodb server for us
services:
  - docker
# command to install dependencies
before_install:
  - docker pull docker.sunet.se/eduid/mongodb:latest
install:
  - python setup.py develop
  - pip install nosexcover WebTest==2.0.18
# command to run tests
script:
  - nosetests
