sudo: required
dist: xenial
addons:
  apt:
    packages:
      xmlsec1  # pysaml2 needs to find an xmlsec1 binary
language: python
python:
  - "3.7"
# Have Travis CI start a mongodb server for us
services:
  - docker
# command to install dependencies
before_install:
  - docker pull docker.sunet.se/eduid/mongodb:latest
install:
  - pip install -U setuptools mypy
  - python setup.py testing
# command to run tests
script:
  - nosetests
  - mypy --ignore-missing-imports src/eduid_idp
